#!/usr/bin/env python3

print("#"*20)
print(" Cloud-init: (Python) Generating Index ")
print("-"*20)

f = open("/var/www/html/index.html","w+")

f.write("Index page generated by <b>Python</b>")

f.close()
