name: Validation

on:
  push:
    branches: [develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: terraform validate
      #   uses: dflook/terraform-validate@v1

      # -name: 'Terraform Init'
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: 0.12.13
      #     tf_actions_subcommand: 'init'
      #     tf_actions_working_dir: '.'
      #     tf_actions_comment: true
      #     args: '-var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}"'
      #     args: '-var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"'
